# Services pour l'intégration Noopy TV

refresh:
  name: Rafraîchir
  description: Force le rafraîchissement des données depuis Noopy TV.

play_channel:
  name: Changer de chaîne
  description: Change la chaîne en cours de lecture sur Noopy TV.
  fields:
    channel_id:
      name: ID de la chaîne
      description: L'identifiant unique (UUID) ou le nom de la chaîne à lire.
      required: true
      example: "TF1"
      selector:
        text:
